* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMDVUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171205T163000Z
  :END:

  <2017-12-05 Tue 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Bi-Weekly Data Science Meeting
  :PROPERTIES:
  :LOCATION: Board Room
  :LINK: [[https://www.google.com/calendar/event?eid=MnZqdGY4NjRzNXMyY2pkNzVvNGtlMmplMmtfMjAxNzEyMDZUMTAwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 2vjtf864s5s2cjd75o4ke2je2k_20171206T100000Z
  :END:

  <2017-12-06 Wed 10:00-10:50>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/154467127

Or iPhone one-tap :
    US: +16699006833,,154467127#  or +14086380968,,154467127#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 669 900 6833  or +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 154 467 127
    International numbers available: https://zoom.us/zoomconference?m=yny9ZgRHJ5Nj1lcEwjop5AI-bibyKJE4

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
        69.174.57.160 (Canada)
    Meeting ID: 154 467 127

    SIP: 154467127@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMDZUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171206T163000Z
  :END:

  <2017-12-06 Wed 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMDdUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171207T163000Z
  :END:

  <2017-12-07 Thu 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMDhUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171208T163000Z
  :END:

  <2017-12-08 Fri 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Gavin - Security & Expectations
  :PROPERTIES:
  :LOCATION: Board Room
  :LINK: [[https://www.google.com/calendar/event?eid=NmxycGdna2xhc3NrM3MwaWtidnBtcDFpcTQgZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 6lrpggklassk3s0ikbvpmp1iq4
  :END:

  <2017-12-11 Mon 11:00-12:00>
* Gavin & Johnny talk about AWS re:Invent 2017
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxNzEyMTFUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20171211T130000Z
  :END:

  <2017-12-11 Mon 13:00-14:00>

<br>Gavin and Johnny talk about their visit to the AWS re:Invent conference.<br>https://reinvent.awsevents.com/<br><br>ZOOM LINK<br><a href="https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F804529409&amp;sa=D&amp;ust=1510147773222000&amp;usg=AFQjCNFdLOTvmLHKR2pqWNGvDcDNdGe8aQ" target="_blank">https://zoom.us/j/804529409</a>
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxNzEyMTFUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20171211T150000Z
  :END:

  <2017-12-11 Mon 15:00-16:00>
* Our Customers
  :PROPERTIES:
  :LOCATION: Board Room
  :LINK: [[https://www.google.com/calendar/event?eid=MGo3N2tpZ2dwbm82OG9yb2YzcTRpNTc2Z3AgZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 0j77kiggpno68orof3q4i576gp
  :END:

  <2017-12-12 Tue 13:30-15:30>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMTJUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171212T163000Z
  :END:

  <2017-12-12 Tue 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Product Show & Tell (demo time)
  :PROPERTIES:
  :LOCATION: by the main office space screen & Zoom: https://zoom.us/j/995277711
  :LINK: [[https://www.google.com/calendar/event?eid=NWdtbGhkcm50aDlnYnVhMmhsYXZwNDhyZWJfMjAxNzEyMTNUMTQwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 5gmlhdrnth9gbua2hlavp48reb_20171213T140000Z
  :END:

  <2017-12-13 Wed 14:00-15:00>

Zoom <a href="https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F995277711&amp;sa=D&amp;ust=1508841621842000&amp;usg=AFQjCNECIcTJNwWWzPXpd_oDW1dlss-b6Q" target="_blank">https://zoom.us/j/995277711</a><br><br>--<br>Hi All, <br><br>Purpose:<br>- With all the work we have been doing to start to change how we are working, one thing we aim to do it to give more visibility of our product software and data team's progress and achievement, as well as increasing awareness of what everyone is working on.<br>-This is a point in time where we'd like to share with the company, all the things the development teams have been working on<br><br>Outcome:<br>Everyone has an understanding of what project and teams we have and what they are working on and how they are doing!<br><br>Teams who will demo each week:<br>Conan, Luigi, Mario, other teams tbh. (the order will change.  Time slot 10 mins each tbc)<br>Agenda:<br>- Each team demos what they have completed in the last 2 weeks (or last iteration).<br>- Each team needs to explain what problem(s) they are solving/their goal and the value solving the problem brings to either our customers or us.<br>- The team will them demo what they did to solve the problem.  If a demo is hard to SHOW, they will TELL you about it.<br>- Sometimes we cannot finish things for various reasons (software is complex!), but we still might learn something, so even if there is no software to demo, we can share what we learned with a TELL<br><br>Attendees: Everyone.  We'd like to make this a cultural event for everyone.<br><br>Frequency: Every two weeks<br><br>If you have any questions, please just ask!<br><br>rgds,<br>Al<br>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMTNUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171213T163000Z
  :END:

  <2017-12-13 Wed 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* MyDrive Christmas Party!!
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=MnZxamRiZGI5MXBmdTFtYmt0YmRyOTM2MGEgZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 2vqjdbdb91pfu1mbktbdr9360a
  :END:

  <2017-12-13 Wed 17:00-22:00>

All will be revealed!
* Our Product & Profiler
  :PROPERTIES:
  :LOCATION: Board Room
  :LINK: [[https://www.google.com/calendar/event?eid=NjVubWVpazRuOGNsZ2ZjaGZoZTc5OXJoajUgZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 65nmeik4n8clgfchfhe799rhj5
  :END:

  <2017-12-14 Thu 10:00-13:00>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMTRUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171214T163000Z
  :END:

  <2017-12-14 Thu 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMTVUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171215T163000Z
  :END:

  <2017-12-15 Fri 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Held for group training session
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxNzEyMThUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20171218T130000Z
  :END:

  <2017-12-18 Mon 13:00-14:00>

Hi everyone,

We would like to establish a weekly one hour training slot on a day that most people are in the office so we can use it for all kinds of 'bit sized' training inputs.

The first session will be a LinkedIn and Social Media Policy training on the 22nd Feb with Anne-Sophie.

Thanks!

ZOOM LINK
https://zoom.us/j/804529409
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxNzEyMThUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20171218T150000Z
  :END:

  <2017-12-18 Mon 15:00-16:00>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMTlUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171219T163000Z
  :END:

  <2017-12-19 Tue 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Bi-Weekly Data Science Meeting
  :PROPERTIES:
  :LOCATION: Board Room
  :LINK: [[https://www.google.com/calendar/event?eid=MnZqdGY4NjRzNXMyY2pkNzVvNGtlMmplMmtfMjAxNzEyMjBUMTAwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 2vjtf864s5s2cjd75o4ke2je2k_20171220T100000Z
  :END:

  <2017-12-20 Wed 10:00-10:50>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/154467127

Or iPhone one-tap :
    US: +16699006833,,154467127#  or +14086380968,,154467127#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 669 900 6833  or +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 154 467 127
    International numbers available: https://zoom.us/zoomconference?m=yny9ZgRHJ5Nj1lcEwjop5AI-bibyKJE4

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
        69.174.57.160 (Canada)
    Meeting ID: 154 467 127

    SIP: 154467127@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMjBUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171220T163000Z
  :END:

  <2017-12-20 Wed 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMjFUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171221T163000Z
  :END:

  <2017-12-21 Thu 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMjJUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171222T163000Z
  :END:

  <2017-12-22 Fri 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Held for group training session
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxNzEyMjVUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20171225T130000Z
  :END:

  <2017-12-25 Mon 13:00-14:00>

Hi everyone,

We would like to establish a weekly one hour training slot on a day that most people are in the office so we can use it for all kinds of 'bit sized' training inputs.

The first session will be a LinkedIn and Social Media Policy training on the 22nd Feb with Anne-Sophie.

Thanks!

ZOOM LINK
https://zoom.us/j/804529409
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxNzEyMjVUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20171225T150000Z
  :END:

  <2017-12-25 Mon 15:00-16:00>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMjZUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171226T163000Z
  :END:

  <2017-12-26 Tue 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Product Show & Tell (demo time)
  :PROPERTIES:
  :LOCATION: by the main office space screen & Zoom: https://zoom.us/j/995277711
  :LINK: [[https://www.google.com/calendar/event?eid=NWdtbGhkcm50aDlnYnVhMmhsYXZwNDhyZWJfMjAxNzEyMjdUMTQwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 5gmlhdrnth9gbua2hlavp48reb_20171227T140000Z
  :END:

  <2017-12-27 Wed 14:00-15:00>

Zoom <a href="https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F995277711&amp;sa=D&amp;ust=1508841621842000&amp;usg=AFQjCNECIcTJNwWWzPXpd_oDW1dlss-b6Q" target="_blank">https://zoom.us/j/995277711</a><br><br>--<br>Hi All, <br><br>Purpose:<br>- With all the work we have been doing to start to change how we are working, one thing we aim to do it to give more visibility of our product software and data team's progress and achievement, as well as increasing awareness of what everyone is working on.<br>-This is a point in time where we'd like to share with the company, all the things the development teams have been working on<br><br>Outcome:<br>Everyone has an understanding of what project and teams we have and what they are working on and how they are doing!<br><br>Teams who will demo each week:<br>Conan, Luigi, Mario, other teams tbh. (the order will change.  Time slot 10 mins each tbc)<br>Agenda:<br>- Each team demos what they have completed in the last 2 weeks (or last iteration).<br>- Each team needs to explain what problem(s) they are solving/their goal and the value solving the problem brings to either our customers or us.<br>- The team will them demo what they did to solve the problem.  If a demo is hard to SHOW, they will TELL you about it.<br>- Sometimes we cannot finish things for various reasons (software is complex!), but we still might learn something, so even if there is no software to demo, we can share what we learned with a TELL<br><br>Attendees: Everyone.  We'd like to make this a cultural event for everyone.<br><br>Frequency: Every two weeks<br><br>If you have any questions, please just ask!<br><br>rgds,<br>Al<br>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMjdUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171227T163000Z
  :END:

  <2017-12-27 Wed 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMjhUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171228T163000Z
  :END:

  <2017-12-28 Thu 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMjlUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171229T163000Z
  :END:

  <2017-12-29 Fri 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Held for group training session
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxODAxMDFUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20180101T130000Z
  :END:

  <2018-01-01 Mon 13:00-14:00>

Hi everyone,

We would like to establish a weekly one hour training slot on a day that most people are in the office so we can use it for all kinds of 'bit sized' training inputs.

The first session will be a LinkedIn and Social Media Policy training on the 22nd Feb with Anne-Sophie.

Thanks!

ZOOM LINK
https://zoom.us/j/804529409
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxODAxMDFUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20180101T150000Z
  :END:

  <2018-01-01 Mon 15:00-16:00>
* Bi-Weekly Data Science Meeting
  :PROPERTIES:
  :LOCATION: Board Room
  :LINK: [[https://www.google.com/calendar/event?eid=MnZqdGY4NjRzNXMyY2pkNzVvNGtlMmplMmtfMjAxODAxMDNUMTAwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 2vjtf864s5s2cjd75o4ke2je2k_20180103T100000Z
  :END:

  <2018-01-03 Wed 10:00-10:50>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/154467127

Or iPhone one-tap :
    US: +16699006833,,154467127#  or +14086380968,,154467127#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 669 900 6833  or +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 154 467 127
    International numbers available: https://zoom.us/zoomconference?m=yny9ZgRHJ5Nj1lcEwjop5AI-bibyKJE4

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
        69.174.57.160 (Canada)
    Meeting ID: 154 467 127

    SIP: 154467127@zoomcrc.com

* Held for group training session
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxODAxMDhUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20180108T130000Z
  :END:

  <2018-01-08 Mon 13:00-14:00>

Hi everyone,

We would like to establish a weekly one hour training slot on a day that most people are in the office so we can use it for all kinds of 'bit sized' training inputs.

The first session will be a LinkedIn and Social Media Policy training on the 22nd Feb with Anne-Sophie.

Thanks!

ZOOM LINK
https://zoom.us/j/804529409
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxODAxMDhUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20180108T150000Z
  :END:

  <2018-01-08 Mon 15:00-16:00>
* Product Show & Tell (demo time)
  :PROPERTIES:
  :LOCATION: by the main office space screen & Zoom: https://zoom.us/j/995277711
  :LINK: [[https://www.google.com/calendar/event?eid=NWdtbGhkcm50aDlnYnVhMmhsYXZwNDhyZWJfMjAxODAxMTBUMTQwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 5gmlhdrnth9gbua2hlavp48reb_20180110T140000Z
  :END:

  <2018-01-10 Wed 14:00-15:00>

Zoom <a href="https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F995277711&amp;sa=D&amp;ust=1508841621842000&amp;usg=AFQjCNECIcTJNwWWzPXpd_oDW1dlss-b6Q" target="_blank">https://zoom.us/j/995277711</a><br><br>--<br>Hi All, <br><br>Purpose:<br>- With all the work we have been doing to start to change how we are working, one thing we aim to do it to give more visibility of our product software and data team's progress and achievement, as well as increasing awareness of what everyone is working on.<br>-This is a point in time where we'd like to share with the company, all the things the development teams have been working on<br><br>Outcome:<br>Everyone has an understanding of what project and teams we have and what they are working on and how they are doing!<br><br>Teams who will demo each week:<br>Conan, Luigi, Mario, other teams tbh. (the order will change.  Time slot 10 mins each tbc)<br>Agenda:<br>- Each team demos what they have completed in the last 2 weeks (or last iteration).<br>- Each team needs to explain what problem(s) they are solving/their goal and the value solving the problem brings to either our customers or us.<br>- The team will them demo what they did to solve the problem.  If a demo is hard to SHOW, they will TELL you about it.<br>- Sometimes we cannot finish things for various reasons (software is complex!), but we still might learn something, so even if there is no software to demo, we can share what we learned with a TELL<br><br>Attendees: Everyone.  We'd like to make this a cultural event for everyone.<br><br>Frequency: Every two weeks<br><br>If you have any questions, please just ask!<br><br>rgds,<br>Al<br>
* Held for group training session
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxODAxMTVUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20180115T130000Z
  :END:

  <2018-01-15 Mon 13:00-14:00>

Hi everyone,

We would like to establish a weekly one hour training slot on a day that most people are in the office so we can use it for all kinds of 'bit sized' training inputs.

The first session will be a LinkedIn and Social Media Policy training on the 22nd Feb with Anne-Sophie.

Thanks!

ZOOM LINK
https://zoom.us/j/804529409
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxODAxMTVUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20180115T150000Z
  :END:

  <2018-01-15 Mon 15:00-16:00>
* Bi-Weekly Data Science Meeting
  :PROPERTIES:
  :LOCATION: Board Room
  :LINK: [[https://www.google.com/calendar/event?eid=MnZqdGY4NjRzNXMyY2pkNzVvNGtlMmplMmtfMjAxODAxMTdUMTAwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 2vjtf864s5s2cjd75o4ke2je2k_20180117T100000Z
  :END:

  <2018-01-17 Wed 10:00-10:50>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/154467127

Or iPhone one-tap :
    US: +16699006833,,154467127#  or +14086380968,,154467127#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 669 900 6833  or +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 154 467 127
    International numbers available: https://zoom.us/zoomconference?m=yny9ZgRHJ5Nj1lcEwjop5AI-bibyKJE4

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
        69.174.57.160 (Canada)
    Meeting ID: 154 467 127

    SIP: 154467127@zoomcrc.com

* Held for group training session
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxODAxMjJUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20180122T130000Z
  :END:

  <2018-01-22 Mon 13:00-14:00>

Hi everyone,

We would like to establish a weekly one hour training slot on a day that most people are in the office so we can use it for all kinds of 'bit sized' training inputs.

The first session will be a LinkedIn and Social Media Policy training on the 22nd Feb with Anne-Sophie.

Thanks!

ZOOM LINK
https://zoom.us/j/804529409
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxODAxMjJUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20180122T150000Z
  :END:

  <2018-01-22 Mon 15:00-16:00>
* Product Show & Tell (demo time)
  :PROPERTIES:
  :LOCATION: by the main office space screen & Zoom: https://zoom.us/j/995277711
  :LINK: [[https://www.google.com/calendar/event?eid=NWdtbGhkcm50aDlnYnVhMmhsYXZwNDhyZWJfMjAxODAxMjRUMTQwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 5gmlhdrnth9gbua2hlavp48reb_20180124T140000Z
  :END:

  <2018-01-24 Wed 14:00-15:00>

Zoom <a href="https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F995277711&amp;sa=D&amp;ust=1508841621842000&amp;usg=AFQjCNECIcTJNwWWzPXpd_oDW1dlss-b6Q" target="_blank">https://zoom.us/j/995277711</a><br><br>--<br>Hi All, <br><br>Purpose:<br>- With all the work we have been doing to start to change how we are working, one thing we aim to do it to give more visibility of our product software and data team's progress and achievement, as well as increasing awareness of what everyone is working on.<br>-This is a point in time where we'd like to share with the company, all the things the development teams have been working on<br><br>Outcome:<br>Everyone has an understanding of what project and teams we have and what they are working on and how they are doing!<br><br>Teams who will demo each week:<br>Conan, Luigi, Mario, other teams tbh. (the order will change.  Time slot 10 mins each tbc)<br>Agenda:<br>- Each team demos what they have completed in the last 2 weeks (or last iteration).<br>- Each team needs to explain what problem(s) they are solving/their goal and the value solving the problem brings to either our customers or us.<br>- The team will them demo what they did to solve the problem.  If a demo is hard to SHOW, they will TELL you about it.<br>- Sometimes we cannot finish things for various reasons (software is complex!), but we still might learn something, so even if there is no software to demo, we can share what we learned with a TELL<br><br>Attendees: Everyone.  We'd like to make this a cultural event for everyone.<br><br>Frequency: Every two weeks<br><br>If you have any questions, please just ask!<br><br>rgds,<br>Al<br>
* Held for group training session
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxODAxMjlUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20180129T130000Z
  :END:

  <2018-01-29 Mon 13:00-14:00>

Hi everyone,

We would like to establish a weekly one hour training slot on a day that most people are in the office so we can use it for all kinds of 'bit sized' training inputs.

The first session will be a LinkedIn and Social Media Policy training on the 22nd Feb with Anne-Sophie.

Thanks!

ZOOM LINK
https://zoom.us/j/804529409
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxODAxMjlUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20180129T150000Z
  :END:

  <2018-01-29 Mon 15:00-16:00>
