* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzExMDJUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171102T163000Z
  :END:

  <2017-11-02 Thu 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzExMDNUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171103T163000Z
  :END:

  <2017-11-03 Fri 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Show and Tell (Moved to Monday as a One Off Session)
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxNzExMDZUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20171106T130000Z
  :END:

  <2017-11-06 Mon 13:00-14:00>

Hi All, <br><br>Purpose:<br>- With all the work we have been doing to start to change how we are working, one thing we aim to do it to give more visibility of our product software and data team's progress and achievement, as well as increasing awareness of what everyone is working on.<br>-This is a point in time where we'd like to share with the company, all the things the development teams have been working on<br><br>Outcome:<br>Everyone has an understanding of what project and teams we have and what they are working on and how they are doing!<br><br>Teams who will demo each week:<br>Conan, Luigi, Mario, other teams tbh. (the order will change. Time slot 10 mins each tbc)<br>Agenda:<br>- Each team demos what they have completed in the last 2 weeks (or last iteration).<br>- Each team needs to explain what problem(s) they are solving/their goal and the value solving the problem brings to either our customers or us.<br>- The team will them demo what they did to solve the problem. If a demo is hard to SHOW, they will TELL you about it.<br>- Sometimes we cannot finish things for various reasons (software is complex!), but we still might learn something, so even if there is no software to demo, we can share what we learned with a TELL<br><br>Attendees: Everyone. We'd like to make this a cultural event for everyone.<br><br>Frequency: Every two weeks<br><br>If you have any questions, please just ask!<br><br>rgds,<br>Al<br><br>ZOOM LINK<br><a href="https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F804529409&amp;sa=D&amp;ust=1509039077642000&amp;usg=AFQjCNEDrhTG0neY7BhRMed4GqWpqjBwqA" target="_blank">https://zoom.us/j/804529409</a>
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxNzExMDZUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20171106T150000Z
  :END:

  <2017-11-06 Mon 15:00-16:00>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzExMDdUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171107T163000Z
  :END:

  <2017-11-07 Tue 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Update on Generali from Linden
  :PROPERTIES:
  :LOCATION: In front of Screen in Main Office
  :LINK: [[https://www.google.com/calendar/event?eid=MGtuNnI4b2htaG5kbjlzc2JwZWR1cWxvZTYgZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 0kn6r8ohmhndn9ssbpeduqloe6
  :END:

  <2017-11-08 Wed 10:30-11:00>

Hi there,

Philippa Cowles is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/483757828

Or iPhone one-tap :
    United Kingdom: +442036950088,,483757828#
Or Telephone:
    Dial(for higher quality, dial a number based on your current location)：
        United Kingdom: +44 (0) 20 3695 0088
    Meeting ID: 483 757 828
    International numbers available: https://zoom.us/zoomconference?m=dbiVlzm4JB0-WsjnAyJFMPSewNlfzbW-

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
        69.174.57.160 (Canada)
    Meeting ID: 483 757 828

    SIP: 483757828@zoomcrc.com

* Gavin Greg 1-1
  :PROPERTIES:
  :LOCATION: Team Room
  :LINK: [[https://www.google.com/calendar/event?eid=NjBrNXVhY3NvYm1oZjA3ajExM3M4dDBoY2kgZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 60k5uacsobmhf07j113s8t0hci
  :END:

  <2017-11-08 Wed 15:30-16:00>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzExMDhUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171108T163000Z
  :END:

  <2017-11-08 Wed 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzExMDlUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171109T163000Z
  :END:

  <2017-11-09 Thu 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Bi-Weekly Data Science Meeting
  :PROPERTIES:
  :LOCATION: Board Room
  :LINK: [[https://www.google.com/calendar/event?eid=MnZqdGY4NjRzNXMyY2pkNzVvNGtlMmplMmtfMjAxNzExMDhUMTAwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 2vjtf864s5s2cjd75o4ke2je2k_20171108T100000Z
  :END:

  <2017-11-10 Fri 13:00-15:00>

<br>This session will be about Best practices for DS. Agenda Below:<br><br><b><p dir="ltr">Workshop on Data Science Best Practices</p><h1 dir="ltr">Version Control</h1><ul><li dir="ltr"><p dir="ltr">Protect the master branch</p></li><li dir="ltr"><p dir="ltr">PR</p><ul><li dir="ltr"><p dir="ltr">Open a WIP PR for visibility </p></li><li dir="ltr"><p dir="ltr">Remove WIP before tagging reviewer</p></li><li dir="ltr"><p dir="ltr">Push fixes to comments, but don’t add additional code to branch under review</p></li><li dir="ltr"><p dir="ltr">Timely review and merge</p></li><li dir="ltr"><p dir="ltr">Descriptions</p></li><li dir="ltr"><p dir="ltr">Keep it small</p></li></ul></li><li dir="ltr"><p dir="ltr">Jupyter Notebooks</p><ul><li dir="ltr"><p dir="ltr">Cleared output before pushing?</p></li></ul></li><li dir="ltr"><p dir="ltr">Advanced(?) Git </p><ul><li dir="ltr"><p dir="ltr">Merge commit Vs rebase</p></li><li dir="ltr"><p dir="ltr">Squash commits</p></li><li dir="ltr"><p dir="ltr">Handling merge conflicts</p></li></ul></li><li dir="ltr"><p dir="ltr">Cleanup of the DS repo</p><ul><li dir="ltr"><p dir="ltr">Repo structure</p></li><li dir="ltr"><p dir="ltr">Project structure</p></li><li dir="ltr"><p dir="ltr">gitignore</p></li></ul></li></ul><h1 dir="ltr">Review Process</h1><ul><li dir="ltr"><p dir="ltr">Code Review</p><ul><li dir="ltr"><p dir="ltr">Accuracy (is this reviewer's responsibility? Why we need testing)</p></li><li dir="ltr"><p dir="ltr">Style - modified PEP8, Flake8 github integration</p></li><li dir="ltr"><p dir="ltr">General good coding practices - naming conventions, modular</p></li><li dir="ltr"><p dir="ltr">Docstrings</p></li><li dir="ltr"><p dir="ltr">What can be taken out into common package</p></li><li dir="ltr"><p dir="ltr">Production/Batch Process? Is the code performant</p><ul><li dir="ltr"><p dir="ltr">Profiling</p></li></ul></li></ul></li><li dir="ltr"><p dir="ltr">Data Science Review</p><ul><li dir="ltr"><p dir="ltr">Is the question well formed?</p></li><li dir="ltr"><p dir="ltr">Have we selected the right data set to answer the question</p></li><li dir="ltr"><p dir="ltr">Have we appropriately cleaned the data?</p></li><li dir="ltr"><p dir="ltr">Is the modelling robust? Sample size, techniques</p></li><li dir="ltr"><p dir="ltr">Have we drawn appropriate conclusions?</p></li></ul></li><li dir="ltr"><p dir="ltr">Communication Review</p><ul><li dir="ltr"><p dir="ltr">Accuracy</p></li><li dir="ltr"><p dir="ltr">Appropriate for the audience</p></li></ul></li></ul><h1 dir="ltr">Testing</h1><ul><li dir="ltr"><p dir="ltr">Different forms</p><ul><li dir="ltr"><p dir="ltr">Data Pipeline</p><ul><li dir="ltr"><p dir="ltr">Standard unit testing (pytest)</p></li></ul></li><li dir="ltr"><p dir="ltr">Data</p><ul><li dir="ltr"><p dir="ltr">Test-Driven Data Analysis (TDDA) - Automatic Constraint Generation and Verification. Also Hypothesis, voluptuous packages</p></li></ul></li><li dir="ltr"><p dir="ltr">Models</p><ul><li dir="ltr"><p dir="ltr">Assert model prediction within range of standard input</p></li></ul></li></ul></li><li dir="ltr"><p dir="ltr">Application of Continuous Integration for subset of work</p><ul><li dir="ltr"><p dir="ltr">Shared packages and potential production code</p></li></ul></li><li dir="ltr"><p dir="ltr">Code Coverage?</p></li></ul><h1 dir="ltr">Reproducibility </h1><ul><li dir="ltr"><p dir="ltr">Access to data</p><ul><li dir="ltr"><p dir="ltr">Stored on s3 by default</p></li><li dir="ltr"><p dir="ltr">Boto3 script / version control of sql queries</p></li></ul></li><li dir="ltr"><p dir="ltr">Package Management</p><ul><li dir="ltr"><p dir="ltr">Conda preferred, pip</p><ul><li dir="ltr"><p dir="ltr">Conda channels (conda-forge, intel, etc.)</p></li></ul></li><li dir="ltr"><p dir="ltr">Environment.yml or Dockerfile in github</p></li><li dir="ltr"><p dir="ltr">Pin package versions</p></li></ul></li><li dir="ltr"><p dir="ltr">Package useful code</p><ul><li dir="ltr"><p dir="ltr">Generally useful across all projects</p></li><li dir="ltr"><p dir="ltr">Within something like progressive project</p></li><li dir="ltr"><p dir="ltr">Conda/pip installable?</p></li><li dir="ltr"><p dir="ltr">Notebook Experimentation Vs Production Code</p></li></ul></li><li dir="ltr"><p dir="ltr">Data pipelines - execute single piece of code to generate features</p><ul><li dir="ltr"><p dir="ltr">make, luigi, airflow, aws step functions?</p></li></ul></li><li dir="ltr"><p dir="ltr">Random seeds</p></li></ul><h1 dir="ltr">Documentation</h1><ul><li dir="ltr"><p dir="ltr">Code</p><ul><li dir="ltr"><p dir="ltr">Docstrings</p></li><li dir="ltr"><p dir="ltr">More formal applies to</p><ul><li dir="ltr"><p dir="ltr">Shared Packages</p></li><li dir="ltr"><p dir="ltr">Feature generation pipeline and Model APIs</p></li></ul></li></ul></li><li dir="ltr"><p dir="ltr">Data Science Research Documents</p><ul><li dir="ltr"><p dir="ltr">Google Docs or Overleaf (allows latex, collaborative editing, git, templates, integration with Mendeley to manage references). </p></li></ul></li></ul><h1 dir="ltr">Security</h1><ul><li dir="ltr"><p dir="ltr">Specifics around roles when using docker containers, otherwise company rules to be complied with.</p></li></ul><h1 dir="ltr">Workflow</h1><p dir="ltr">Although the way in which we manage projects is closely related to many of the topics above we’ll consider it out of scope for this discussion and something to be picked up with an Agile Coach.</p><p dir="ltr"></p></b><br><br><br><br><br><br><br><br><br><br><br><br><br>Hi there, <br><br>Zoulficar Younes is inviting you to a scheduled Zoom meeting. <br><br>Join from PC, Mac, Linux, iOS or Android: <a href="https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F154467127&amp;sa=D&amp;ust=1508762875884000&amp;usg=AFQjCNGaqTjZCuMkoF8CAZr-kq1ThK2KcA" target="_blank">https://zoom.us/j/154467127</a><br><br>Or iPhone one-tap :<br>    US: +16699006833,,154467127#  or +14086380968,,154467127# <br>Or Telephone：<br>    Dial(for higher quality, dial a number based on your current location)：<br>        US: +1 669 900 6833  or +1 408 638 0968  or +1 646 876 9923 <br>    Meeting ID: 154 467 127<br>    International numbers available: <a href="https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fzoomconference%3Fm%3Dyny9ZgRHJ5Nj1lcEwjop5AI-bibyKJE4&amp;sa=D&amp;ust=1508762875884000&amp;usg=AFQjCNGU4Z0_Ot5Eqr29A_lZkGtM9NCt_Q" target="_blank">https://zoom.us/zoomconference?m=yny9ZgRHJ5Nj1lcEwjop5AI-bibyKJE4</a><br><br>Or an H.323/SIP room system:<br>    H.323: <br>        162.255.37.11 (US West)<br>        162.255.36.11 (US East)<br>        221.122.88.195 (China)<br>        115.114.131.7 (India)<br>        213.19.144.110 (EMEA)<br>        202.177.207.158 (Australia)<br>        209.9.211.110 (Hong Kong)<br>        64.211.144.160 (Brazil)<br>        69.174.57.160 (Canada)<br>    Meeting ID: 154 467 127<br><br>    SIP: <a href="mailto:154467127@zoomcrc.com" target="_blank">154467127@zoomcrc.com</a><br><br>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzExMTBUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171110T163000Z
  :END:

  <2017-11-10 Fri 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Anne-Sophie & Nada talk about Web Summit 2017
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxNzExMTNUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20171113T130000Z
  :END:

  <2017-11-13 Mon 13:00-14:00>

Anne-Sophie and Nada talk about their visit to Web Summit 2017<br><br>ZOOM LINK<br><a href="https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F804529409&amp;sa=D&amp;ust=1510147773212000&amp;usg=AFQjCNH6E1Sskly6HVdH0RW7llwYLJJ7Hw" target="_blank">https://zoom.us/j/804529409</a>
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxNzExMTNUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20171113T150000Z
  :END:

  <2017-11-13 Mon 15:00-16:00>
* Board Games Night
  :PROPERTIES:
  :LOCATION: Board Room
  :LINK: [[https://www.google.com/calendar/event?eid=NHQ4YjBidjEzbXF0bmx0NWFzM2swcGhwMWUgZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 4t8b0bv13mqtnlt5as3k0php1e
  :END:

  <2017-11-13 Mon 17:00-19:50>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzExMTRUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171114T163000Z
  :END:

  <2017-11-14 Tue 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* DS Best Practices Workshop
  :PROPERTIES:
  :LOCATION: Customer Room
  :LINK: [[https://www.google.com/calendar/event?eid=MzZ0NmEwM2JxYmdiZWZza3R0MnN1aDh2c3AgZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 36t6a03bqbgbefsktt2suh8vsp
  :END:

  <2017-11-15 Wed 10:00-12:00>
* Lunch!
  :PROPERTIES:
  :LOCATION: Honest Burgers - Covent Garden, 33 Southampton St, London WC2E 7HE, United Kingdom
  :LINK: [[https://www.google.com/calendar/event?eid=NmtwbTZwOWw2Y28zY2I5bGM1Z200YjlrYzVpamdiOW9jOHM2YWJiMWNoajNjZDFqY2dxNjZjOWhjayBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 6kpm6p9l6co3cb9lc5gm4b9kc5ijgb9oc8s6abb1chj3cd1jcgq66c9hck
  :END:

  <2017-11-15 Wed 13:00-14:00>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzExMTVUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171115T163000Z
  :END:

  <2017-11-15 Wed 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Quick catch-up
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/872615758, Board Room
  :LINK: [[https://www.google.com/calendar/event?eid=NjRxNDkyOGM2aDYzZmc2cmszZmZjcWN1M3QgZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 64q4928c6h63fg6rk3ffcqcu3t
  :END:

  <2017-11-16 Thu 13:30-14:00>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/872615758

Or iPhone one-tap :
    US: +16699006833,,872615758#  or +14086380968,,872615758#
Or Telephone:
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 669 900 6833  or +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 872 615 758
    International numbers available: https://zoom.us/zoomconference?m=ym9J2ulRGMgwUOqxDXqGVzKHhglBNJg9

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
        69.174.57.160 (Canada)
    Meeting ID: 872 615 758

    SIP: 872615758@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzExMTZUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171116T163000Z
  :END:

  <2017-11-16 Thu 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Tim Ryan visit to MyDrive
  :PROPERTIES:
  :LOCATION: MyDrive Solutions Ltd, Unit 02.02.1, The Leather Market, Weston St, London SE1 3ER, UK
  :LINK: [[https://www.google.com/calendar/event?eid=MzgydW1pbjZwaTcxM2FtYWZqdmlscm45dWwgZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 382umin6pi713amafjvilrn9ul
  :END:

  <2017-11-17 Fri>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzExMTdUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171117T163000Z
  :END:

  <2017-11-17 Fri 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Matthew Hinks leaving drinks
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=MGxvdjBna203bGVnMmh0ZTEzcGEwZWxuZGwgZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 0lov0gkm7leg2hte13pa0elndl
  :END:

  <2017-11-17 Fri 17:00-20:00>
* WFH
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=N3ZkaGhlN2UwM3E3Y3FwcXN2aWQzNDVlaWUgZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 7vdhhe7e03q7cqpqsvid345eie
  :END:

  <2017-11-20 Mon 08:00-12:30>
* Carly - Office Policy Update
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxNzExMjBUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20171120T130000Z
  :END:

  <2017-11-20 Mon 13:00-14:00>

Carly will go through the key points of our updated office policy!<br><br><br>ZOOM LINK<br><a href="https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F804529409&amp;sa=D&amp;ust=1510830442046000&amp;usg=AFQjCNHcxM1NW098119GPzp17yUH__pYbA" target="_blank">https://zoom.us/j/804529409</a>
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxNzExMjBUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20171120T150000Z
  :END:

  <2017-11-20 Mon 15:00-16:00>
* New Joiner UX Session
  :PROPERTIES:
  :LOCATION: Upstairs on mezzanine
  :LINK: [[https://www.google.com/calendar/event?eid=N2FhdG1kMjFtOTNvbjd2c28xNTRiMWMwN2MgZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 7aatmd21m93on7vso154b1c07c
  :END:

  <2017-11-20 Mon 16:00-17:00>

Dear all,<p>As part of your onboarding, I'd like to invite you to a session to learn about UX. Some of you might already know some things about UX but I promise you will learn some stuff.<br></p><p>I did this session back in March with the whole team and it was quite fun.</p><p><br></p><p><br></p>
* Gavin Greg 1-1
  :PROPERTIES:
  :LOCATION: Customer Room
  :LINK: [[https://www.google.com/calendar/event?eid=NDY2anBwOWdnN2tsNm51aTRhZHV1OWloZG8gZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 466jpp9gg7kl6nui4aduu9ihdo
  :END:

  <2017-11-21 Tue 10:30-11:00>

Hi there, <br><br>Gavin Heavyside is inviting you to a scheduled Zoom meeting. <br><br>Join from PC, Mac, Linux, iOS or Android: <a href="https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F583518640&amp;sa=D&amp;ust=1511114569168000&amp;usg=AFQjCNHiovNQpnyYzfMMON6GM_XJZE8vjw" target="_blank">https://zoom.us/j/583518640</a><br><br>Or iPhone one-tap :<br>    United Kingdom: +442036950088,,583518640# <br>Or Telephone:<br>    Dial(for higher quality, dial a number based on your current location)：<br>        United Kingdom: +44 (0) 20 3695 0088 <br>    Meeting ID: 583 518 640<br>    International numbers available: <a href="https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fzoomconference%3Fm%3De_qSzJJP8eWoRJndUIa5PqzY9BDa2x6C&amp;sa=D&amp;ust=1511114569168000&amp;usg=AFQjCNGoSrcu8tuUzn5RF9_rLZX04UWiZw" target="_blank">https://zoom.us/zoomconference?m=e_qSzJJP8eWoRJndUIa5PqzY9BDa2x6C</a><br><br>Or an H.323/SIP room system:<br>    H.323: <br>        162.255.37.11 (US West)<br>        162.255.36.11 (US East)<br>        221.122.88.195 (China)<br>        115.114.131.7 (India)<br>        213.19.144.110 (EMEA)<br>        202.177.207.158 (Australia)<br>        209.9.211.110 (Hong Kong)<br>        64.211.144.160 (Brazil)<br>        69.174.57.160 (Canada)<br>    Meeting ID: 583 518 640<br><br>    SIP: <a href="mailto:583518640@zoomcrc.com" target="_blank">583518640@zoomcrc.com</a><br><br>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzExMjFUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171121T163000Z
  :END:

  <2017-11-21 Tue 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Scaling the pipeline discussion
  :PROPERTIES:
  :LOCATION: Board Room
  :LINK: [[https://www.google.com/calendar/event?eid=NHRhb3ZwMnIyZ3RjcnFmYzBjNGc2Y2llYW4gZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 4taovp2r2gtcrqfc0c4g6ciean
  :END:

  <2017-11-22 Wed 15:30-17:00>

Next year we are going to be delivering to Brazil and we want to ensure we can cope with the scale challenges this will introduce.<br><br>Agenda:<br><ol><li>Introduction and background<br></li><li>Review previous scaling work done<br></li><li>Explain major changes since then<br></li><li>Discussion of work to be done</li></ol><br>So we are all clear though, this is about evolution, not revolution. The next generation of our pipeline is likely to look extremely different, I don't want us to re-engineer how the entire pipeline works, I want us to improve, and make more robust, what we already have.<br>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzExMjJUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171122T163000Z
  :END:

  <2017-11-22 Wed 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* MyDrive Wine Tasting!
  :PROPERTIES:
  :LOCATION: In the office
  :LINK: [[https://www.google.com/calendar/event?eid=NjU1cG9wcjkwc3Y2NTRiNm0zbWJicXFpaWsgZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 655popr90sv654b6m3mbbqqiik
  :END:

  <2017-11-22 Wed 17:00-20:00>

Following the success of last year's wine tasting, we will be hosting another one this year! Learning from the connoisseur's themselves, Mike, Anne-Sophie and Nhan they shall take us on a journey to explore the different regions, grape varieties and styles of all the wines. It will be BYOB (bring your own booze) and we will put on some nibbles also to match with your wines :) More info to follow!
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzExMjNUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171123T163000Z
  :END:

  <2017-11-23 Thu 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* wfh
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=NTA3OHVhNWtjdmdpYXBzMWpwbTQ5aG43cm0gZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 5078ua5kcvgiaps1jpm49hn7rm
  :END:

  <2017-11-24 Fri 09:00-17:00>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzExMjRUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171124T163000Z
  :END:

  <2017-11-24 Fri 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Anthony 30mins briefing about PDP
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxNzExMjdUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20171127T130000Z
  :END:

  <2017-11-27 Mon 13:00-14:00>

Anthony will give a 30mins talk about our personal development plans.<br><br>ZOOM LINK<br><a href="https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F804529409&amp;sa=D&amp;ust=1511442715659000&amp;usg=AFQjCNGo9JKGDpZjgnAPbahCX8v1UkaKfA" target="_blank">https://zoom.us/j/804529409</a>
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxNzExMjdUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20171127T150000Z
  :END:

  <2017-11-27 Mon 15:00-16:00>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzExMjhUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171128T163000Z
  :END:

  <2017-11-28 Tue 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Product Show & Tell (demo time)
  :PROPERTIES:
  :LOCATION: by the main office space screen & Zoom: https://zoom.us/j/995277711
  :LINK: [[https://www.google.com/calendar/event?eid=NWdtbGhkcm50aDlnYnVhMmhsYXZwNDhyZWJfMjAxNzExMjlUMTQwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 5gmlhdrnth9gbua2hlavp48reb_20171129T140000Z
  :END:

  <2017-11-29 Wed 14:00-15:00>

Zoom <a href="https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F995277711&amp;sa=D&amp;ust=1508841621842000&amp;usg=AFQjCNECIcTJNwWWzPXpd_oDW1dlss-b6Q" target="_blank">https://zoom.us/j/995277711</a><br><br>--<br>Hi All, <br><br>Purpose:<br>- With all the work we have been doing to start to change how we are working, one thing we aim to do it to give more visibility of our product software and data team's progress and achievement, as well as increasing awareness of what everyone is working on.<br>-This is a point in time where we'd like to share with the company, all the things the development teams have been working on<br><br>Outcome:<br>Everyone has an understanding of what project and teams we have and what they are working on and how they are doing!<br><br>Teams who will demo each week:<br>Conan, Luigi, Mario, other teams tbh. (the order will change.  Time slot 10 mins each tbc)<br>Agenda:<br>- Each team demos what they have completed in the last 2 weeks (or last iteration).<br>- Each team needs to explain what problem(s) they are solving/their goal and the value solving the problem brings to either our customers or us.<br>- The team will them demo what they did to solve the problem.  If a demo is hard to SHOW, they will TELL you about it.<br>- Sometimes we cannot finish things for various reasons (software is complex!), but we still might learn something, so even if there is no software to demo, we can share what we learned with a TELL<br><br>Attendees: Everyone.  We'd like to make this a cultural event for everyone.<br><br>Frequency: Every two weeks<br><br>If you have any questions, please just ask!<br><br>rgds,<br>Al<br>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzExMjlUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171129T163000Z
  :END:

  <2017-11-29 Wed 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* wfh
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=MGlhb21yMGFmY2w2a3NybzZjcXQ5a3VwdmIgZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 0iaomr0afcl6ksro6cqt9kupvb
  :END:

  <2017-11-30 Thu>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzExMzBUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171130T163000Z
  :END:

  <2017-11-30 Thu 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMDFUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171201T163000Z
  :END:

  <2017-12-01 Fri 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Held for group training session
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxNzEyMDRUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20171204T130000Z
  :END:

  <2017-12-04 Mon 13:00-14:00>

Hi everyone,

We would like to establish a weekly one hour training slot on a day that most people are in the office so we can use it for all kinds of 'bit sized' training inputs.

The first session will be a LinkedIn and Social Media Policy training on the 22nd Feb with Anne-Sophie.

Thanks!

ZOOM LINK
https://zoom.us/j/804529409
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxNzEyMDRUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20171204T150000Z
  :END:

  <2017-12-04 Mon 15:00-16:00>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMDVUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171205T163000Z
  :END:

  <2017-12-05 Tue 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Bi-Weekly Data Science Meeting
  :PROPERTIES:
  :LOCATION: Board Room
  :LINK: [[https://www.google.com/calendar/event?eid=MnZqdGY4NjRzNXMyY2pkNzVvNGtlMmplMmtfMjAxNzEyMDZUMTAwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 2vjtf864s5s2cjd75o4ke2je2k_20171206T100000Z
  :END:

  <2017-12-06 Wed 10:00-10:50>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/154467127

Or iPhone one-tap :
    US: +16699006833,,154467127#  or +14086380968,,154467127#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 669 900 6833  or +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 154 467 127
    International numbers available: https://zoom.us/zoomconference?m=yny9ZgRHJ5Nj1lcEwjop5AI-bibyKJE4

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
        69.174.57.160 (Canada)
    Meeting ID: 154 467 127

    SIP: 154467127@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMDZUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171206T163000Z
  :END:

  <2017-12-06 Wed 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMDdUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171207T163000Z
  :END:

  <2017-12-07 Thu 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMDhUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171208T163000Z
  :END:

  <2017-12-08 Fri 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Gavin - Security & Expectations
  :PROPERTIES:
  :LOCATION: Board Room
  :LINK: [[https://www.google.com/calendar/event?eid=NmxycGdna2xhc3NrM3MwaWtidnBtcDFpcTQgZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 6lrpggklassk3s0ikbvpmp1iq4
  :END:

  <2017-12-11 Mon 11:00-12:00>
* Gavin & Johnny talk about AWS re:Invent 2017
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxNzEyMTFUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20171211T130000Z
  :END:

  <2017-12-11 Mon 13:00-14:00>

<br>Gavin and Johnny talk about their visit to the AWS re:Invent conference.<br>https://reinvent.awsevents.com/<br><br>ZOOM LINK<br><a href="https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F804529409&amp;sa=D&amp;ust=1510147773222000&amp;usg=AFQjCNFdLOTvmLHKR2pqWNGvDcDNdGe8aQ" target="_blank">https://zoom.us/j/804529409</a>
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxNzEyMTFUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20171211T150000Z
  :END:

  <2017-12-11 Mon 15:00-16:00>
* Our Customers
  :PROPERTIES:
  :LOCATION: Board Room
  :LINK: [[https://www.google.com/calendar/event?eid=MGo3N2tpZ2dwbm82OG9yb2YzcTRpNTc2Z3AgZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 0j77kiggpno68orof3q4i576gp
  :END:

  <2017-12-12 Tue 13:30-15:30>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMTJUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171212T163000Z
  :END:

  <2017-12-12 Tue 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Product Show & Tell (demo time)
  :PROPERTIES:
  :LOCATION: by the main office space screen & Zoom: https://zoom.us/j/995277711
  :LINK: [[https://www.google.com/calendar/event?eid=NWdtbGhkcm50aDlnYnVhMmhsYXZwNDhyZWJfMjAxNzEyMTNUMTQwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 5gmlhdrnth9gbua2hlavp48reb_20171213T140000Z
  :END:

  <2017-12-13 Wed 14:00-15:00>

Zoom <a href="https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F995277711&amp;sa=D&amp;ust=1508841621842000&amp;usg=AFQjCNECIcTJNwWWzPXpd_oDW1dlss-b6Q" target="_blank">https://zoom.us/j/995277711</a><br><br>--<br>Hi All, <br><br>Purpose:<br>- With all the work we have been doing to start to change how we are working, one thing we aim to do it to give more visibility of our product software and data team's progress and achievement, as well as increasing awareness of what everyone is working on.<br>-This is a point in time where we'd like to share with the company, all the things the development teams have been working on<br><br>Outcome:<br>Everyone has an understanding of what project and teams we have and what they are working on and how they are doing!<br><br>Teams who will demo each week:<br>Conan, Luigi, Mario, other teams tbh. (the order will change.  Time slot 10 mins each tbc)<br>Agenda:<br>- Each team demos what they have completed in the last 2 weeks (or last iteration).<br>- Each team needs to explain what problem(s) they are solving/their goal and the value solving the problem brings to either our customers or us.<br>- The team will them demo what they did to solve the problem.  If a demo is hard to SHOW, they will TELL you about it.<br>- Sometimes we cannot finish things for various reasons (software is complex!), but we still might learn something, so even if there is no software to demo, we can share what we learned with a TELL<br><br>Attendees: Everyone.  We'd like to make this a cultural event for everyone.<br><br>Frequency: Every two weeks<br><br>If you have any questions, please just ask!<br><br>rgds,<br>Al<br>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMTNUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171213T163000Z
  :END:

  <2017-12-13 Wed 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* MyDrive Christmas Party!!
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=MnZxamRiZGI5MXBmdTFtYmt0YmRyOTM2MGEgZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 2vqjdbdb91pfu1mbktbdr9360a
  :END:

  <2017-12-13 Wed 17:00-22:00>

All will be revealed!
* Our Product & Profiler
  :PROPERTIES:
  :LOCATION: Board Room
  :LINK: [[https://www.google.com/calendar/event?eid=NjVubWVpazRuOGNsZ2ZjaGZoZTc5OXJoajUgZ3JlZy5ud29zdUBteWRyaXZlc29sdXRpb25zLmNvbQ][Go to gcal web page]]
  :ID: 65nmeik4n8clgfchfhe799rhj5
  :END:

  <2017-12-14 Thu 10:00-13:00>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMTRUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171214T163000Z
  :END:

  <2017-12-14 Thu 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMTVUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171215T163000Z
  :END:

  <2017-12-15 Fri 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Held for group training session
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxNzEyMThUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20171218T130000Z
  :END:

  <2017-12-18 Mon 13:00-14:00>

Hi everyone,

We would like to establish a weekly one hour training slot on a day that most people are in the office so we can use it for all kinds of 'bit sized' training inputs.

The first session will be a LinkedIn and Social Media Policy training on the 22nd Feb with Anne-Sophie.

Thanks!

ZOOM LINK
https://zoom.us/j/804529409
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxNzEyMThUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20171218T150000Z
  :END:

  <2017-12-18 Mon 15:00-16:00>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMTlUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171219T163000Z
  :END:

  <2017-12-19 Tue 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Bi-Weekly Data Science Meeting
  :PROPERTIES:
  :LOCATION: Board Room
  :LINK: [[https://www.google.com/calendar/event?eid=MnZqdGY4NjRzNXMyY2pkNzVvNGtlMmplMmtfMjAxNzEyMjBUMTAwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 2vjtf864s5s2cjd75o4ke2je2k_20171220T100000Z
  :END:

  <2017-12-20 Wed 10:00-10:50>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/154467127

Or iPhone one-tap :
    US: +16699006833,,154467127#  or +14086380968,,154467127#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 669 900 6833  or +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 154 467 127
    International numbers available: https://zoom.us/zoomconference?m=yny9ZgRHJ5Nj1lcEwjop5AI-bibyKJE4

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
        69.174.57.160 (Canada)
    Meeting ID: 154 467 127

    SIP: 154467127@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMjBUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171220T163000Z
  :END:

  <2017-12-20 Wed 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMjFUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171221T163000Z
  :END:

  <2017-12-21 Thu 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMjJUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171222T163000Z
  :END:

  <2017-12-22 Fri 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Held for group training session
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxNzEyMjVUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20171225T130000Z
  :END:

  <2017-12-25 Mon 13:00-14:00>

Hi everyone,

We would like to establish a weekly one hour training slot on a day that most people are in the office so we can use it for all kinds of 'bit sized' training inputs.

The first session will be a LinkedIn and Social Media Policy training on the 22nd Feb with Anne-Sophie.

Thanks!

ZOOM LINK
https://zoom.us/j/804529409
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxNzEyMjVUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20171225T150000Z
  :END:

  <2017-12-25 Mon 15:00-16:00>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMjZUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171226T163000Z
  :END:

  <2017-12-26 Tue 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Product Show & Tell (demo time)
  :PROPERTIES:
  :LOCATION: by the main office space screen & Zoom: https://zoom.us/j/995277711
  :LINK: [[https://www.google.com/calendar/event?eid=NWdtbGhkcm50aDlnYnVhMmhsYXZwNDhyZWJfMjAxNzEyMjdUMTQwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 5gmlhdrnth9gbua2hlavp48reb_20171227T140000Z
  :END:

  <2017-12-27 Wed 14:00-15:00>

Zoom <a href="https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F995277711&amp;sa=D&amp;ust=1508841621842000&amp;usg=AFQjCNECIcTJNwWWzPXpd_oDW1dlss-b6Q" target="_blank">https://zoom.us/j/995277711</a><br><br>--<br>Hi All, <br><br>Purpose:<br>- With all the work we have been doing to start to change how we are working, one thing we aim to do it to give more visibility of our product software and data team's progress and achievement, as well as increasing awareness of what everyone is working on.<br>-This is a point in time where we'd like to share with the company, all the things the development teams have been working on<br><br>Outcome:<br>Everyone has an understanding of what project and teams we have and what they are working on and how they are doing!<br><br>Teams who will demo each week:<br>Conan, Luigi, Mario, other teams tbh. (the order will change.  Time slot 10 mins each tbc)<br>Agenda:<br>- Each team demos what they have completed in the last 2 weeks (or last iteration).<br>- Each team needs to explain what problem(s) they are solving/their goal and the value solving the problem brings to either our customers or us.<br>- The team will them demo what they did to solve the problem.  If a demo is hard to SHOW, they will TELL you about it.<br>- Sometimes we cannot finish things for various reasons (software is complex!), but we still might learn something, so even if there is no software to demo, we can share what we learned with a TELL<br><br>Attendees: Everyone.  We'd like to make this a cultural event for everyone.<br><br>Frequency: Every two weeks<br><br>If you have any questions, please just ask!<br><br>rgds,<br>Al<br>
* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMjdUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171227T163000Z
  :END:

  <2017-12-27 Wed 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMjhUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171228T163000Z
  :END:

  <2017-12-28 Thu 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* DS Standup
  :PROPERTIES:
  :LOCATION: https://zoom.us/j/534345752
  :LINK: [[https://www.google.com/calendar/event?eid=NG5mbGEzaThsZmY2bXMyYmU0bzEyaTk5MXNfMjAxNzEyMjlUMTYzMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 4nfla3i8lff6ms2be4o12i991s_20171229T163000Z
  :END:

  <2017-12-29 Fri 16:30-16:45>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/534345752

Or iPhone one-tap :
    US: +14086380968,,534345752#  or +16468769923,,534345752#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 534 345 752
    International numbers available: https://zoom.us/zoomconference?m=h6GNN2PgPxLv4vRF-fozo85C33H4xNo6

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
    Meeting ID: 534 345 752

    SIP: 534345752@zoomcrc.com

* Held for group training session
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxODAxMDFUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20180101T130000Z
  :END:

  <2018-01-01 Mon 13:00-14:00>

Hi everyone,

We would like to establish a weekly one hour training slot on a day that most people are in the office so we can use it for all kinds of 'bit sized' training inputs.

The first session will be a LinkedIn and Social Media Policy training on the 22nd Feb with Anne-Sophie.

Thanks!

ZOOM LINK
https://zoom.us/j/804529409
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxODAxMDFUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20180101T150000Z
  :END:

  <2018-01-01 Mon 15:00-16:00>
* Bi-Weekly Data Science Meeting
  :PROPERTIES:
  :LOCATION: Board Room
  :LINK: [[https://www.google.com/calendar/event?eid=MnZqdGY4NjRzNXMyY2pkNzVvNGtlMmplMmtfMjAxODAxMDNUMTAwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 2vjtf864s5s2cjd75o4ke2je2k_20180103T100000Z
  :END:

  <2018-01-03 Wed 10:00-10:50>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/154467127

Or iPhone one-tap :
    US: +16699006833,,154467127#  or +14086380968,,154467127#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 669 900 6833  or +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 154 467 127
    International numbers available: https://zoom.us/zoomconference?m=yny9ZgRHJ5Nj1lcEwjop5AI-bibyKJE4

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
        69.174.57.160 (Canada)
    Meeting ID: 154 467 127

    SIP: 154467127@zoomcrc.com

* Held for group training session
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxODAxMDhUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20180108T130000Z
  :END:

  <2018-01-08 Mon 13:00-14:00>

Hi everyone,

We would like to establish a weekly one hour training slot on a day that most people are in the office so we can use it for all kinds of 'bit sized' training inputs.

The first session will be a LinkedIn and Social Media Policy training on the 22nd Feb with Anne-Sophie.

Thanks!

ZOOM LINK
https://zoom.us/j/804529409
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxODAxMDhUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20180108T150000Z
  :END:

  <2018-01-08 Mon 15:00-16:00>
* Product Show & Tell (demo time)
  :PROPERTIES:
  :LOCATION: by the main office space screen & Zoom: https://zoom.us/j/995277711
  :LINK: [[https://www.google.com/calendar/event?eid=NWdtbGhkcm50aDlnYnVhMmhsYXZwNDhyZWJfMjAxODAxMTBUMTQwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 5gmlhdrnth9gbua2hlavp48reb_20180110T140000Z
  :END:

  <2018-01-10 Wed 14:00-15:00>

Zoom <a href="https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F995277711&amp;sa=D&amp;ust=1508841621842000&amp;usg=AFQjCNECIcTJNwWWzPXpd_oDW1dlss-b6Q" target="_blank">https://zoom.us/j/995277711</a><br><br>--<br>Hi All, <br><br>Purpose:<br>- With all the work we have been doing to start to change how we are working, one thing we aim to do it to give more visibility of our product software and data team's progress and achievement, as well as increasing awareness of what everyone is working on.<br>-This is a point in time where we'd like to share with the company, all the things the development teams have been working on<br><br>Outcome:<br>Everyone has an understanding of what project and teams we have and what they are working on and how they are doing!<br><br>Teams who will demo each week:<br>Conan, Luigi, Mario, other teams tbh. (the order will change.  Time slot 10 mins each tbc)<br>Agenda:<br>- Each team demos what they have completed in the last 2 weeks (or last iteration).<br>- Each team needs to explain what problem(s) they are solving/their goal and the value solving the problem brings to either our customers or us.<br>- The team will them demo what they did to solve the problem.  If a demo is hard to SHOW, they will TELL you about it.<br>- Sometimes we cannot finish things for various reasons (software is complex!), but we still might learn something, so even if there is no software to demo, we can share what we learned with a TELL<br><br>Attendees: Everyone.  We'd like to make this a cultural event for everyone.<br><br>Frequency: Every two weeks<br><br>If you have any questions, please just ask!<br><br>rgds,<br>Al<br>
* Held for group training session
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxODAxMTVUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20180115T130000Z
  :END:

  <2018-01-15 Mon 13:00-14:00>

Hi everyone,

We would like to establish a weekly one hour training slot on a day that most people are in the office so we can use it for all kinds of 'bit sized' training inputs.

The first session will be a LinkedIn and Social Media Policy training on the 22nd Feb with Anne-Sophie.

Thanks!

ZOOM LINK
https://zoom.us/j/804529409
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxODAxMTVUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20180115T150000Z
  :END:

  <2018-01-15 Mon 15:00-16:00>
* Bi-Weekly Data Science Meeting
  :PROPERTIES:
  :LOCATION: Board Room
  :LINK: [[https://www.google.com/calendar/event?eid=MnZqdGY4NjRzNXMyY2pkNzVvNGtlMmplMmtfMjAxODAxMTdUMTAwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 2vjtf864s5s2cjd75o4ke2je2k_20180117T100000Z
  :END:

  <2018-01-17 Wed 10:00-10:50>

Hi there,

Zoulficar Younes is inviting you to a scheduled Zoom meeting.

Join from PC, Mac, Linux, iOS or Android: https://zoom.us/j/154467127

Or iPhone one-tap :
    US: +16699006833,,154467127#  or +14086380968,,154467127#
Or Telephone：
    Dial(for higher quality, dial a number based on your current location)：
        US: +1 669 900 6833  or +1 408 638 0968  or +1 646 876 9923
    Meeting ID: 154 467 127
    International numbers available: https://zoom.us/zoomconference?m=yny9ZgRHJ5Nj1lcEwjop5AI-bibyKJE4

Or an H.323/SIP room system:
    H.323:
        162.255.37.11 (US West)
        162.255.36.11 (US East)
        221.122.88.195 (China)
        115.114.131.7 (India)
        213.19.144.110 (EMEA)
        202.177.207.158 (Australia)
        209.9.211.110 (Hong Kong)
        64.211.144.160 (Brazil)
        69.174.57.160 (Canada)
    Meeting ID: 154 467 127

    SIP: 154467127@zoomcrc.com

* Held for group training session
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxODAxMjJUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20180122T130000Z
  :END:

  <2018-01-22 Mon 13:00-14:00>

Hi everyone,

We would like to establish a weekly one hour training slot on a day that most people are in the office so we can use it for all kinds of 'bit sized' training inputs.

The first session will be a LinkedIn and Social Media Policy training on the 22nd Feb with Anne-Sophie.

Thanks!

ZOOM LINK
https://zoom.us/j/804529409
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxODAxMjJUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20180122T150000Z
  :END:

  <2018-01-22 Mon 15:00-16:00>
* Product Show & Tell (demo time)
  :PROPERTIES:
  :LOCATION: by the main office space screen & Zoom: https://zoom.us/j/995277711
  :LINK: [[https://www.google.com/calendar/event?eid=NWdtbGhkcm50aDlnYnVhMmhsYXZwNDhyZWJfMjAxODAxMjRUMTQwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 5gmlhdrnth9gbua2hlavp48reb_20180124T140000Z
  :END:

  <2018-01-24 Wed 14:00-15:00>

Zoom <a href="https://www.google.com/url?q=https%3A%2F%2Fzoom.us%2Fj%2F995277711&amp;sa=D&amp;ust=1508841621842000&amp;usg=AFQjCNECIcTJNwWWzPXpd_oDW1dlss-b6Q" target="_blank">https://zoom.us/j/995277711</a><br><br>--<br>Hi All, <br><br>Purpose:<br>- With all the work we have been doing to start to change how we are working, one thing we aim to do it to give more visibility of our product software and data team's progress and achievement, as well as increasing awareness of what everyone is working on.<br>-This is a point in time where we'd like to share with the company, all the things the development teams have been working on<br><br>Outcome:<br>Everyone has an understanding of what project and teams we have and what they are working on and how they are doing!<br><br>Teams who will demo each week:<br>Conan, Luigi, Mario, other teams tbh. (the order will change.  Time slot 10 mins each tbc)<br>Agenda:<br>- Each team demos what they have completed in the last 2 weeks (or last iteration).<br>- Each team needs to explain what problem(s) they are solving/their goal and the value solving the problem brings to either our customers or us.<br>- The team will them demo what they did to solve the problem.  If a demo is hard to SHOW, they will TELL you about it.<br>- Sometimes we cannot finish things for various reasons (software is complex!), but we still might learn something, so even if there is no software to demo, we can share what we learned with a TELL<br><br>Attendees: Everyone.  We'd like to make this a cultural event for everyone.<br><br>Frequency: Every two weeks<br><br>If you have any questions, please just ask!<br><br>rgds,<br>Al<br>
* Held for group training session
  :PROPERTIES:
  :LOCATION: The office
  :LINK: [[https://www.google.com/calendar/event?eid=ZWsxZDU3c2RzNWhpZGhudmdjOTV0OGVoZnNfMjAxODAxMjlUMTMwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: ek1d57sds5hidhnvgc95t8ehfs_20180129T130000Z
  :END:

  <2018-01-29 Mon 13:00-14:00>

Hi everyone,

We would like to establish a weekly one hour training slot on a day that most people are in the office so we can use it for all kinds of 'bit sized' training inputs.

The first session will be a LinkedIn and Social Media Policy training on the 22nd Feb with Anne-Sophie.

Thanks!

ZOOM LINK
https://zoom.us/j/804529409
* Profiler Evolution - weekly catch-up
  :PROPERTIES:
  :LINK: [[https://www.google.com/calendar/event?eid=M2llcGsxNXQ0YWprMWZybmtjaXZqZWRjZWlfMjAxODAxMjlUMTUwMDAwWiBncmVnLm53b3N1QG15ZHJpdmVzb2x1dGlvbnMuY29t][Go to gcal web page]]
  :ID: 3iepk15t4ajk1frnkcivjedcei_20180129T150000Z
  :END:

  <2018-01-29 Mon 15:00-16:00>
